# Generated by Django 5.2.2 on 2025-06-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=2, help_text='Current meter reading in kWh', max_digits=10)),
                ('previous_reading_value', models.DecimalField(blank=True, decimal_places=2, help_text='Meter reading value from the last bill', max_digits=10, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated consumption (current - previous)', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=3, help_text='Price per kWh at the time of reading', max_digits=6)),
                ('is_billed', models.BooleanField(default=False, help_text='Has a bill been generated for this reading period?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_readings', to='billing.tenant')),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
                'unique_together': {('tenant', 'reading_date')},
            },
        ),
    ]
