# Generated by Django 5.2.2 on 2025-06-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_electricityreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fixed_water_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fixed monthly water charge for this tenant. Leave blank or 0 if not applicable or included in rent.', max_digits=7, null=True),
        ),
    ]
