# Generated by Django 5.2.2 on 2025-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_tenant_fixed_water_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fixed_wifi_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fixed monthly WiFi charge for this tenant. Leave blank or 0 if not applicable.', max_digits=7, null=True),
        ),
    ]
